name: Gerar Releases
#usa a função de releases do próprio github
#o caminho é: git tag v1.0.0 -> git push origin v1.0.0 (após a main estar atualizada para essa versão)

on:
  push:
    tags:
      - 'v*'   # dispara quando você fizer push de uma tag tipo v1.0.0 sinalizando versão

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write   # necessário para criar releases
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 

      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn -B clean package -DskipTests

      - name: Criar Release e anexar JAR
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: target/*.jar